# apiVersion: v1
# kind: Namespace
# metadata:
#   name: roboshop
#   labels:
#     project: roboshop
#     environment: dev
#     purpose: poc


apiVersion: v1
kind: Namespace
metadata:
  name: rakesh
  labels:
    project: k8s
    envritonmrnt: dev
    purporse: poc